/** Базовые данные сайта (CMS). Поля в snake_case — как в ТЗ. */
export const DEFAULT_DATA = {
  ui: {
    nav_home: "Главная",
    nav_services: "Услуги",
    nav_about: "О компании",
    nav_contacts: "Контакты",
    nav_cta: "Оставить заявку",
    services_all_link: "Все услуги →",
    industries_eyebrow: "Отрасли",
    industries_title: "Все виды продукции",
    industries_sub: "Сертификация и испытания по действующим регламентам РУз",
    process_eyebrow: "Как мы работаем",
    process_title: "От заявки до сертификата",
    services_home_eyebrow: "Что мы делаем",
    services_home_title: "Наши услуги",
    about_home_eyebrow: "О компании",
    about_home_btn1: "Подробнее о компании",
    about_home_btn2: "Связаться",
    about_info_title: "Базовая информация",
    why_badge: "№1",
    why_eyebrow: "Почему мы",
    why_title: "Надёжный партнёр по сертификации",
    numbers_eyebrow: "В цифрах",
    clients_eyebrow: "Клиенты",
    clients_title: "Нам доверяют производители и импортёры",
    clients_sub: "Работаем с компаниями из разных отраслей и юрисдикций.",
    reviews_eyebrow: "Отзывы",
    reviews_title: "Клиенты о работе с нами",
    reviews_sub: "Реальные компании из разных стран — о сроках и качестве сопровождения.",
    footer_services: "Услуги",
    footer_company: "Компания",
    footer_contacts: "Контакты",
    footer_cta_services: "Все услуги",
    footer_cta_about: "О компании",
    footer_cta_contacts: "Контакты",
    footer_rights: "© Electro Class Control. Все права защищены.",
    page_services_eyebrow: "Услуги",
    page_services_title: "Полный спектр сертификации",
    page_services_sub: "Подберём оптимальный маршрут оформления документов под вашу продукцию и рынок.",
    page_about_eyebrow: "О компании",
    page_about_title: "История и команда",
    page_about_sub: "Аккредитованный центр сертификации и испытательная лаборатория с 2009 года.",
    page_contacts_eyebrow: "Контакты",
    page_contacts_title: "Свяжитесь с нами",
    page_contacts_sub: "Оставьте заявку — ответим в течение 2 рабочих часов.",
    contacts_form_title: "Заявка на консультацию",
    contacts_form_submit: "Отправить",
    contacts_labels_address: "Адрес:",
    contacts_labels_hours: "Режим:",
    contacts_labels_accred: "Аккредитация:",
    contacts_labels_phone: "Телефон:",
    contacts_labels_email: "Email:",
    cta_success_title: "Заявка отправлена",
    cta_success_text: "Мы свяжемся с вами в ближайшее время.",
    admin_title: "Редактирование контента",
    admin_save: "💾 Сохранить",
    admin_reset: "↩ Сброс",
    admin_close: "Закрыть",
    admin_tabs: {
      general: "🏢 Основное",
      services: "🛠 Услуги",
      hero: "🎯 Герой",
      contacts: "📞 Контакты",
      design: "🎨 Дизайн",
    },
  },
  company: {
    name: "Electro Class Control",
    sub: "Сертификация · Лаборатория",
    accred: "Аккредитация № УзА-ОС-2009-0114",
    address_short: "г. Ташкент, ул. Нукусская, 89",
    address_full: "г. Ташкент, ул. Нукусская, 89, офис 305, БЦ «Нукус Плаза»",
    workhours: "Пн–Пт 9:00–18:00",
    phone: "+998 71 234-56-78",
    phone_link: "998712345678",
    email: "info@ecc-cert.uz",
    telegram: "ecc_cert_uz",
    whatsapp: "998712345678",
    desc: "Аккредитованный центр сертификации и испытательная лаборатория в Ташкенте с 2009 года.",
    usp_img: "https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=800&q=80",
    about_img: "https://images.unsplash.com/photo-1600880292203-757bb62b4baf?w=800&q=80",
    map_img: "https://images.unsplash.com/photo-1526778548025-fa2f459cd5ce?w=700&q=80",
    video_url: "https://www.youtube.com/embed/dQw4w9WgXcQ",
  },
  hero: {
    badge: "Аккредитованный орган · Ташкент",
    h1_pre: "Сертификация и испытания продукции в",
    h1_mark: "Узбекистане",
    sub: "Получите разрешительную документацию для ввоза или производства товаров — под ключ, в срок, по регламенту РУз.",
    btn1: "Узнать стоимость",
    btn2: "Написать в WhatsApp",
    trust: [
      { num: "2400+", lbl: "выданных сертификатов" },
      { num: "15", lbl: "лет на рынке" },
      { num: "30+", lbl: "стран-партнёров" },
      { num: "5 дней", lbl: "минимальный срок" },
    ],
  },
  numbers: [
    { val: "2400+", lbl: "выданных сертификатов" },
    { val: "15", lbl: "лет на рынке РУз" },
    { val: "30+", lbl: "стран-клиентов" },
    { val: "12", lbl: "отраслей аккредитации" },
  ],
  services: [
    {
      id: 1,
      tag: "Сертификация",
      name: "Сертификация продукции",
      desc: "Оформляем сертификаты и декларации соответствия по всем ТР РУз — электротехника, текстиль, пищевые продукты, машиностроение, полимеры.",
      time: "⏱ от 5 рабочих дней",
      img: "https://images.unsplash.com/photo-1581092334651-ddf26d9a09d0?w=600&q=80",
    },
    {
      id: 2,
      tag: "Лаборатория",
      name: "Лабораторные испытания",
      desc: "Аккредитованная лаборатория — испытания образцов с выдачей протокола. Физические, химические, биологические показатели.",
      time: "⏱ от 3 рабочих дней",
      img: "https://images.unsplash.com/photo-1532187863486-abf9dbad1b69?w=600&q=80",
    },
    {
      id: 3,
      tag: "Импорт",
      name: "Документы для импорта",
      desc: "Полный пакет для таможенного оформления ввозимых товаров в Узбекистан. Работаем удалённо из любой страны.",
      time: "⏱ удалённо, из любой страны",
      img: "https://images.unsplash.com/photo-1578575437130-527eed3abbec?w=600&q=80",
    },
  ],
  usp: [
    { ico: "⚡", title: "Срок от 5 рабочих дней", text: "Срочное оформление — от 3 дней при доплате 30%." },
    { ico: "💰", title: "Гибкая цена под бюджет", text: "Оплата в сумах, долларах, рублях. Постоплата для постоянных клиентов." },
    { ico: "📦", title: "Полный пакет документов", text: "Сертификат, декларация, протокол, переводы — всё для таможни в одном месте." },
    { ico: "🌍", title: "Работаем с 30+ странами", text: "Образцы принимаем курьером. Документы отправляем электронно." },
  ],
  clients: [
    "Agro Capital",
    "UzTex Holding",
    "Silk Road Foods",
    "BuildUz Pro",
    "TashMed Group",
    "Orient Pharma",
    "PolyTex UZ",
    "GreenField Co",
    "MachinePoint",
    "FoodExport TR",
  ],
  client_countries: ["🇨🇳 Китай", "🇷🇺 Россия", "🇹🇷 Турция", "🇩🇪 Германия", "🇦🇪 ОАЭ", "🇰🇿 Казахстан", "🇧🇾 Беларусь", "🇮🇹 Италия"],
  industries: [
    { ico: "⚡", name: "Электротехника" },
    { ico: "🧵", name: "Текстиль и одежда" },
    { ico: "🍞", name: "Пищевая продукция" },
    { ico: "⚙️", name: "Машиностроение" },
    { ico: "🧪", name: "Полимеры и химия" },
    { ico: "🏗", name: "Стройматериалы" },
    { ico: "🩺", name: "Медицинские изделия" },
    { ico: "🧸", name: "Детские товары" },
    { ico: "🛢", name: "Нефтехимия" },
    { ico: "🌿", name: "Экоэкспертиза" },
    { ico: "🔥", name: "Пожарная безопасность" },
    { ico: "📦", name: "Упаковка и тара" },
  ],
  process: [
    { num: "1", title: "Заявка", desc: "Отвечаем в течение 2 часов" },
    { num: "2", title: "Документы", desc: "Проверяем техдокументацию и образцы" },
    { num: "3", title: "Испытания", desc: "Проводим лабораторные испытания" },
    { num: "4", title: "Сертификат", desc: "Выдаём итоговый пакет документов" },
  ],
  video_section: {
    eyebrow: "Видео",
    title: "Как мы сопровождаем сертификацию",
    text: "Коротко о процессе: от первичной консультации до выдачи сертификата и передачи пакета для таможни.",
    btn_about: "О компании",
  },
  reviews: [
    {
      text: "Оформили пакет для ввоза электроники из Китая за 6 рабочих дней. Всё прозрачно, без сюрпризов на таможне.",
      name: "Алексей К.",
      org: "ImportTech CN",
      flag: "🇨🇳",
      avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=120&q=80",
    },
    {
      text: "Лабораторные протоколы и сертификат получили дистанционно. Удобная коммуникация в Telegram.",
      name: "Марина С.",
      org: "Silk Road Foods",
      flag: "🇷🇺",
      avatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=120&q=80",
    },
    {
      text: "Работали по текстилю: сроки соблюдены, стоимость согласовали заранее. Рекомендуем как надёжного партнёра.",
      name: "Эмре Д.",
      org: "Orient Textile TR",
      flag: "🇹🇷",
      avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=120&q=80",
    },
  ],
  cta: {
    title: "Готовы начать сертификацию?",
    sub: "Оставьте заявку — подготовим коммерческое предложение и чек-лист документов.",
    bullets: ["Ответ в течение 2 часов", "Прозрачная смета без скрытых платежей", "Сопровождение до выдачи документов"],
    phone_note: "Или позвоните:",
    form_title: "Быстрая заявка",
    fields: {
      product: "Тип товара",
      country: "Страна",
      messenger: "Telegram / WhatsApp",
      email: "Email",
    },
    placeholders: {
      product: "Электроника, одежда, продукты…",
      messenger: "+998 XX XXX-XX-XX",
      email: "you@company.com",
    },
    submit: "Отправить заявку",
  },
  consult_countries: [
    { value: "", label: "Выберите…", disabled: true },
    { value: "ru", label: "Россия" },
    { value: "cn", label: "Китай" },
    { value: "tr", label: "Турция" },
    { value: "kz", label: "Казахстан" },
    { value: "de", label: "Германия" },
    { value: "other", label: "Другая" },
  ],
  about_page: {
    history_title: "История",
    history: [
      "С 2009 года Electro Class Control помогает производителям и импортёрам получать разрешительную документацию в Узбекистане.",
      "Мы развиваем лабораторную базу и расширяем область аккредитации, чтобы закрывать запросы разных отраслей в одном окне.",
    ],
    accreditations_title: "Аккредитации",
    accreditations: [
      { title: "Центр сертификации", desc: "Оформление сертификатов и деклараций соответствия по регламентам РУз." },
      { title: "Испытательная лаборатория", desc: "Протоколы испытаний для подтверждения показателей безопасности и качества." },
      { title: "Международное сотрудничество", desc: "Работа с образцами и документами из 30+ стран, электронный документооборот." },
    ],
    team_title: "Команда",
    team: [
      { name: "Директор по сертификации", role: "Руководство направлением", photo: "https://images.unsplash.com/photo-1560250097-0b93528c311a?w=400&q=80" },
      { name: "Главный инженер лаборатории", role: "Методология испытаний", photo: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=400&q=80" },
      { name: "Менеджер клиентского сервиса", role: "Сопровождение заявок", photo: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=400&q=80" },
      { name: "Специалист по ВЭД", role: "Импорт и таможня", photo: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&q=80" },
    ],
  },
  design: {
    navy: "#0B1F3A",
    blue: "#1854C4",
    accent: "#E85D04",
    light: "#F9FAFB",
  },
};
